spring:
  datasource:
    url: jdbc:sqlserver://sbfsd-server.database.windows.net:1433;database=SBFSD-DB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: myuser
    password: YasirAjmal@123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191